[32mINFO    [0m juju.model:model.py:2097 Deploying ch:amd64/focal/indico-175
[32mINFO    [0m juju.model:model.py:2097 Deploying ch:amd64/focal/redis-k8s-7
[32mINFO    [0m juju.model:model.py:2097 Deploying ch:amd64/focal/redis-k8s-7
[33mWARNING [0m juju.model:model.py:1563 relate is deprecated and will be removed. Use integrate instead.
[33mWARNING [0m juju.model:model.py:1563 relate is deprecated and will be removed. Use integrate instead.
[32mINFO    [0m juju.model:model.py:2957 Waiting for model:
  indico/0 [allocating] waiting: installing agent
[32mINFO    [0m juju.model:model.py:2957 Waiting for model:
  indico/0 [allocating] waiting: installing agent
[32mINFO    [0m juju.model:model.py:2957 Waiting for model:
  indico/0 [idle] waiting: Waiting for database availability
[32mINFO    [0m juju.model:model.py:2957 Waiting for model:
  indico/0 [idle] waiting: Waiting for database availability
[32mINFO    [0m integration.new_relations.test_new_relations:test_new_relations.py:693 Verifying that the charm doesn't block when the extensions are enabled
[32mINFO    [0m juju.model:model.py:2957 Waiting for model:
  database/0 [idle] active: Primary
  database/1 [executing] active: 
  database/2 [executing] active: 
[32mINFO    [0m juju.model:model.py:2957 Waiting for model:
  database/0 [idle] active: Primary
  database/1 [idle] active: 
  database/2 [idle] active: 
[33mWARNING [0m juju.model:model.py:1563 relate is deprecated and will be removed. Use integrate instead.
[32mINFO    [0m juju.model:model.py:2957 Waiting for model:
  database/0 [executing] active: Primary
  database/1 [executing] active: 
  database/2 [executing] active: 
  indico/0 [executing] waiting: Waiting for database availability
[32mINFO    [0m juju.model:model.py:2957 Waiting for model:
  database/0 [idle] active: Primary
  database/1 [idle] active: 
  database/2 [idle] active: 
  indico/0 [executing] maintenance: Adding indico-celery layer to pebble
[32mINFO    [0m juju.model:model.py:2957 Waiting for model:
  indico/0 [idle] active:
[32mINFO    [0m pytest_operator.plugin:plugin.py:791 Model status:

Model  Controller          Cloud/Region        Version  SLA          Timestamp
test   microk8s-localhost  microk8s/localhost  3.1.7    unsupported  02:03:41Z

App                      Version               Status   Scale  Charm                Channel        Rev  Address         Exposed  Message
another-application                            active       1  postgresql-test-app  edge            75  10.152.183.151  no       received database credentials of the first database
another-data-integrator                        waiting      1  data-integrator      latest/stable   19  10.152.183.253  no       installing agent
another-database         14.11                 active       3  postgresql-k8s                        0  10.152.183.91   no       Primary
data-integrator                                waiting      1  data-integrator      latest/stable   19  10.152.183.94   no       installing agent
database                 14.11                 active       3  postgresql-k8s                        1  10.152.183.36   no       Primary
indico                   3.2.8                 active       1  indico               stable         175  10.152.183.208  no       
other-discourse-k8s      3.2.0                 active       1  discourse-k8s        latest/stable   95  10.152.183.26   no       
postgresql-test-app                            active       2  postgresql-test-app  edge            75  10.152.183.99   no       received database credentials of the first database
redis-broker             ubuntu/redis@691f315  active       1  redis-k8s            stable           7                  no       
redis-cache              ubuntu/redis@691f315  active       1  redis-k8s            stable           7                  no       
redis-k8s                7.0.4                 active       1  redis-k8s            latest/edge     27  10.152.183.183  no       

Unit                        Workload  Agent  Address      Ports     Message
another-application/0*      active    idle   10.1.35.150            received database credentials of the first database
another-data-integrator/0*  blocked   idle   10.1.35.154            Please relate the data-integrator with the desired product
another-database/0*         active    idle   10.1.35.143            Primary
another-database/1          active    idle   10.1.35.144            
another-database/2          active    idle   10.1.35.145            
data-integrator/0*          blocked   idle   10.1.35.153            Please relate the data-integrator with the desired product
database/0*                 active    idle   10.1.35.147            Primary
database/1                  active    idle   10.1.35.151            
database/2                  active    idle   10.1.35.152            
indico/0*                   active    idle   10.1.35.162            
other-discourse-k8s/0*      active    idle   10.1.35.158            
postgresql-test-app/0*      active    idle   10.1.35.136            received database credentials of the first database
postgresql-test-app/1       active    idle   10.1.35.137            received database credentials of the first database
redis-broker/0*             active    idle   10.1.35.163  6379/TCP  
redis-cache/0*              active    idle   10.1.35.165  6379/TCP  
redis-k8s/0*                active    idle   10.1.35.157            

[32mINFO    [0m pytest_operator.plugin:plugin.py:797 Juju error logs:

unit-database-0: 01:47:04 ERROR unit.database/0.juju-log database:20: Invalid extra user roles: test
unit-database-0: 01:47:04 ERROR unit.database/0.juju-log database:20: invalid role(s) for extra user roles
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-database-0/charm/src/relations/postgresql_provider.py", line 90, in _on_database_requested
    self.charm.postgresql.create_user(user, password, extra_user_roles=extra_user_roles)
  File "/var/lib/juju/agents/unit-database-0/charm/lib/charms/postgresql_k8s/v0/postgresql.py", line 221, in create_user
    raise PostgreSQLCreateUserError(INVALID_EXTRA_USER_ROLE_BLOCKING_MESSAGE)
charms.postgresql_k8s.v0.postgresql.PostgreSQLCreateUserError: invalid role(s) for extra user roles
unit-database-0: 01:47:10 ERROR unit.database/0.juju-log database:21: Invalid extra user roles: test
unit-database-0: 01:47:10 ERROR unit.database/0.juju-log database:21: invalid role(s) for extra user roles
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-database-0/charm/src/relations/postgresql_provider.py", line 90, in _on_database_requested
    self.charm.postgresql.create_user(user, password, extra_user_roles=extra_user_roles)
  File "/var/lib/juju/agents/unit-database-0/charm/lib/charms/postgresql_k8s/v0/postgresql.py", line 221, in create_user
    raise PostgreSQLCreateUserError(INVALID_EXTRA_USER_ROLE_BLOCKING_MESSAGE)
charms.postgresql_k8s.v0.postgresql.PostgreSQLCreateUserError: invalid role(s) for extra user roles
application-redis-cache: 02:01:33 ERROR unit.redis-cache/0.juju-log redis:31: Uncaught exception while in charm code:
Traceback (most recent call last):
  File "./src/charm.py", line 159, in <module>
    main(RedisCharm)
  File "/var/lib/juju/agents/unit-redis-cache-0/charm/venv/ops/main.py", line 402, in main
    _emit_charm_event(charm, dispatcher.event_name)
  File "/var/lib/juju/agents/unit-redis-cache-0/charm/venv/ops/main.py", line 140, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-redis-cache-0/charm/venv/ops/framework.py", line 278, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-redis-cache-0/charm/venv/ops/framework.py", line 722, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-redis-cache-0/charm/venv/ops/framework.py", line 767, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-redis-cache-0/charm/lib/charms/redis_k8s/v0/redis.py", line 91, in _on_relation_changed
    event.relation.data[self.model.unit]['hostname'] = str(self._bind_address(event))
  File "/var/lib/juju/agents/unit-redis-cache-0/charm/lib/charms/redis_k8s/v0/redis.py", line 103, in _bind_address
    return self.app.name
AttributeError: 'RedisProvides' object has no attribute 'app'
application-redis-cache: 02:01:33 ERROR juju.worker.caasoperator.uniter.redis-cache/0.operation hook "redis-relation-changed" (via hook dispatching script: dispatch) failed: exit status 1

[32mINFO    [0m pytest_operator.plugin:plugin.py:861 Forgetting main...