[32mINFO    [0m pytest_operator.plugin:plugin.py:734 Connecting to existing model microk8s-localhost:test on unspecified cloud
[32mINFO    [0m juju.model:model.py:2098 Deploying local:jammy/postgresql-k8s-0
[32mINFO    [0m juju.model:model.py:2958 Waiting for model:
  postgresql-k8s/0 [allocating] waiting: installing agent
[32mINFO    [0m juju.model:model.py:2958 Waiting for model:
  postgresql-k8s/0 [executing] waiting: awaiting for cluster to start
[32mINFO    [0m juju.model:model.py:2958 Waiting for model:
  postgresql-k8s/0 [idle] waiting: awaiting for cluster to start
[32mINFO    [0m juju.model:model.py:2958 Waiting for model:
  postgresql-k8s/0 [idle] active: Primary
[32mINFO    [0m integration.test_config:test_config.py:92 durability_synchronous_commit
[32mINFO    [0m juju.model:model.py:2958 Waiting for model:
  postgresql-k8s/0 [idle] active: Primary
[32mINFO    [0m pytest_operator.plugin:plugin.py:862 Model status:

Model  Controller          Cloud/Region        Version  SLA          Timestamp
test   microk8s-localhost  microk8s/localhost  3.1.8    unsupported  01:34:08Z

App             Version  Status  Scale  Charm           Channel  Rev  Address        Exposed  Message
postgresql-k8s  14.11    error       1  postgresql-k8s             0  10.152.183.75  no       hook failed: "upgrade-relation-changed"

Unit               Workload  Agent  Address     Ports  Message
postgresql-k8s/0*  error     idle   10.1.13.73         hook failed: "upgrade-relation-changed"

[32mINFO    [0m pytest_operator.plugin:plugin.py:868 Juju error logs:

unit-postgresql-k8s-0: 01:34:06 ERROR unit.postgresql-k8s/0.juju-log Invalid configuration: 1 validation error for CharmConfig
durability_synchronous_commit
  Value not one of 'on', 'remote_apply' or 'remote_write' (type=value_error)
unit-postgresql-k8s-0: 01:34:07 ERROR unit.postgresql-k8s/0.juju-log upgrade:0: Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-k8s-0/charm/./src/charm.py", line 1633, in <module>
    main(PostgresqlOperatorCharm, use_juju_for_storage=True)
  File "/var/lib/juju/agents/unit-postgresql-k8s-0/charm/venv/ops/main.py", line 544, in main
    manager.run()
  File "/var/lib/juju/agents/unit-postgresql-k8s-0/charm/venv/ops/main.py", line 520, in run
    self._emit()
  File "/var/lib/juju/agents/unit-postgresql-k8s-0/charm/venv/ops/main.py", line 509, in _emit
    _emit_charm_event(self.charm, self.dispatcher.event_name)
  File "/var/lib/juju/agents/unit-postgresql-k8s-0/charm/venv/ops/main.py", line 143, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-postgresql-k8s-0/charm/venv/ops/framework.py", line 352, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-postgresql-k8s-0/charm/venv/ops/framework.py", line 851, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-postgresql-k8s-0/charm/venv/ops/framework.py", line 941, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-postgresql-k8s-0/charm/src/upgrade.py", line 134, in _on_upgrade_changed
    self.charm.update_config()
  File "/var/lib/juju/agents/unit-postgresql-k8s-0/charm/./src/charm.py", line 1403, in update_config
    if self.config.profile_limit_memory:
  File "/var/lib/juju/agents/unit-postgresql-k8s-0/charm/lib/charms/data_platform_libs/v0/data_models.py", line 200, in config
    return self.config_type(**translated_keys)
  File "/var/lib/juju/agents/unit-postgresql-k8s-0/charm/venv/pydantic/main.py", line 341, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for CharmConfig
durability_synchronous_commit
  Value not one of 'on', 'remote_apply' or 'remote_write' (type=value_error)

[32mINFO    [0m pytest_operator.plugin:plugin.py:947 Forgetting model main...